{{- if .Values.persistence.gitlabData.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab.fullname" . }}-data
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.gitlabData.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.gitlabData.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabData.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabData.size | quote }}
{{- end }}
---
{{- if .Values.persistence.gitlabEtc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "gitlab.fullname" . }}-etc
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.gitlabEtc.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.gitlabEtc.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabEtc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabEtc.size | quote }}
{{- end }}
