apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if default "" .Values.gitlabRootPassword }}
  # Defaulting to a non-sensical value to silence b64enc warning. We'll never
  # actually use this default due to the if statement.
  gitlab-root-password: {{ default "ignore" .Values.gitlabRootPassword | b64enc | quote }}
  {{ end }}
  db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.redisPassword | b64enc | quote }}
