apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))}}
    nodePort: {{.Values.service.nodePort}}
    {{end}}
  - name: ssh
    port: {{ .Values.service.sshPort | int }}
    targetPort: ssh
  - name: https
    port: {{ .Values.service.httpsPort | int }}
    targetPort: https
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
